### ISSUE TITLE
Doesn't seem to install on Windows 10

### ISSUE THREAD

**Issue by Venryx** [lucidcode/LucidScribe-OpenEEG#1]
Doesn't seem to install the actual executable file on Windows 10.

I used the installer here: https://lucidcode.com/2015/01/06/openeeg-1-0-1/

Here's a screenshot of the install folder: http://i.imgur.com/dbdp96O.png

Only dlls...

**Comment by Venryx** [comment]
Btw, super cool that you have a rich framework set up already for EEG monitoring and resulting actions.

With your project for desktop, and mine for mobile, there's now options for both platforms, which is nice. (though mine is still in its infant stage)

What format, if any, are you using for storing eeg data after a night's worth of sleep? I'm curious, as I haven't yet implemented data recording in my app, and it would be nice to use a standardized format. (e.g. for having compatible save files between our systems)

**Comment by IAmCoder** [comment]
You will also need Lucid Scribe itself: https://lucidcode.com/category/software/lucid-scribe/

I rolled my own... LSD: http://shell.windows.com/fileassoc/fileassoc.asp?Ext=LSD 8D
You can download a collection from LSDBase... they are human readable and just show the hours (h) and minutes (m): https://lsdbase.org/category/hardware/openeeg/
But most other researchers use EDF - Lucid Scribe has an option to export to that.

I would also be happy to write a converter for you if you go with another format like I did for another DVer:
https://github.com/Nazrax/DreamMaskV4/tree/master/Lucid%20Scribe%20Data%20Converter

Can you give the Muse plugin a shot? I only tested it by replaying recordings... so they also have their own format.

**Comment by Venryx** [comment]
Thanks for the links, I'll take a look at those options when I get around to data recording.

As for trying out the Muse plugin: Will do! Not sure exactly when. It's probably pretty fast, but I'm in a sort of lazy rut at the moment.

Software development is great, but some days I get lazy; tonight I'll attempt something relatively easy, which is adding a basic dream journal feature to my app. (not quite ready to do the "Tracker" feature, which would require recording data and deciding on how to lay out the charts and data-points for long periods)

Ugh, I'm in the mood for a lucid dream right now.

**Comment by Venryx** [comment]
Okay, I'm less annoyed with myself now; dream journal feature is added!

Now I can go to bed at least not feeling completely unproductive. : P

**Comment by IAmCoder** [comment]
I feel you. Best part of the search for lucidity is that you don't have to go to sleep anymore - you go to research!
